### ISSUE TITLE
gsp-resources plugin not working with bundle

### ISSUE THREAD

**Issue by skreiker** [mckenfra/gsp-resources#4]
I am using the gsp-resources plugin and if I create a module in ApplicationResources.groovy with the .js files and .js.gsp files then the .js.gsp file do not get bundled with the .js file

Here is my code

In ApplicationResources.groovy I have

modules = {
    application {
        resource url:'js/application.js'
        resource url:'js/testresource.js.gsp'
    }

in a view test.gsp I have
        <r:require module='application'/>  
        <r:layoutResources />
        <r:layoutResources />

If I look at the redenred gsp file the js file and the js.gsp files are not bundled in one single file

**Comment by mckenfra** [comment]
Thanks very much for raising this. I've just pushed out a fix with version `0.4.2-SNAPSHOT`. Please could you see if it fixes your issue? You will need to include the following line in `BuildConfig.groovy`:

```
runtime ':gsp-resources:0.4.2-SNAPSHOT'
```

**Comment by kapitall** [comment]
I just tested, It is working better but still failing if the bundle contains a js file after the js.gsp file

This works
application {
resource url:'js/application.js'
resource url:'js/testresource.js.gsp'
}

This throws an erroe
application {
resource url:'js/testresource.js.gsp'
resource url:'js/application.js'
}

Error is 
Resource reload failed!:
java.lang.NullPointerException
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.plus(DefaultGroovyMethods.java:12848)
    at org.codehaus.groovy.runtime.dgm$595.doMethodInvoke(Unknown Source)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1071)
    at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:901)
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.sum(DefaultGroovyMethods.java:3979)
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.sum(DefaultGroovyMethods.java:3900)
    at org.codehaus.groovy.runtime.dgm$777.invoke(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
    at org.grails.plugin.resource.AggregatedResourceMeta.beginPrepare(AggregatedResourceMeta.groovy:70)
    at org.grails.plugin.resource.JavaScriptBundleResourceMeta.beginPrepare(JavaScriptBundleResourceMeta.groovy)
    at org.grails.plugin.resource.AggregatedResourceMeta$beginPrepare.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
    at org.grails.plugin.resource.ResourceMeta$beginPrepare.call(Unknown Source)
    at org.grails.plugin.resource.ResourceProcessor.prepareResource(ResourceProcessor.groovy:531)
    at org.grails.plugin.gspresources.GspResourceProcessor.prepareResource(GspResourceProcessor.groovy)
    at sun.reflect.GeneratedMethodAccessor439.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.springsource.loaded.ri.OriginalClassInvoker.invoke(OriginalClassInvoker.java:34)
    at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1260)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1071)
    at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:901)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
    at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:901)
    at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:145)
    at org.grails.plugin.resource.ResourceProcessor$_prepareSingleDeclaredResource_closure12.doCall(ResourceProcessor.groovy:610)
    at sun.reflect.GeneratedMethodAccessor458.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.springsource.loaded.ri.OriginalClassInvoker.invoke(OriginalClassInvoker.java:34)
    at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1260)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1071)
    at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:901)
    at groovy.lang.Closure.call(Closure.java:415)
    at org.grails.plugin.resource.ResourceProcessor$_prepareSingleDeclaredResource_closure12.call(ResourceProcessor.groovy)
    at groovy.lang.Closure.call(Closure.java:409)
    at org.grails.plugin.resource.ResourceProcessor$_prepareSingleDeclaredResource_closure12.call(ResourceProcessor.groovy)
    at java_util_concurrent_Callable$call.call(Unknown Source)
    at org.grails.plugin.resource.util.ResourceMetaStore.addDeclaredResource(ResourceMetaStore.groovy:29)
    at org.grails.plugin.resource.util.ResourceMetaStore$addDeclaredResource.call(Unknown Source)
    at org.grails.plugin.resource.ResourceProcessor.prepareSingleDeclaredResource(ResourceProcessor.groovy:608)
    at org.grails.plugin.gspresources.GspResourceProcessor.prepareSingleDeclaredResource(GspResourceProcessor.groovy)
    at org.grails.plugin.resource.ResourceProcessor$prepareSingleDeclaredResource.callCurrent(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:46)
    at org.grails.plugin.resource.ResourceProcessor$prepareSingleDeclaredResource.callCurrent(Unknown Source)
    at org.grails.plugin.resource.ResourceProcessor.prepareResourceBatch(ResourceProcessor.groovy:657)
    at org.grails.plugin.gspresources.GspResourceProcessor.super$2$prepareResourceBatch(GspResourceProcessor.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.springsource.loaded.ri.OriginalClassInvoker.invoke(OriginalClassInvoker.java:34)
    at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1260)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1071)
    at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:128)
    at org.grails.plugin.gspresources.GspResourceProcessor.prepareResourceBatch(GspResourceProcessor.groovy:231)
    at org.grails.plugin.gspresources.GspResourceProcessor$prepareResourceBatch.callCurrent(Unknown Source)
    at org.grails.plugin.resource.ResourceProcessor.resourcesChanged(ResourceProcessor.groovy:813)
    at org.grails.plugin.resource.ResourceProcessor.this$2$resourcesChanged(ResourceProcessor.groovy)
    at org.grails.plugin.gspresources.GspResourceProcessor.this$2$resourcesChanged(GspResourceProcessor.groovy)
    at org.grails.plugin.resource.ResourceProcessor$this$2$resourcesChanged.callCurrent(Unknown Source)
    at org.grails.plugin.resource.ResourceProcessor.loadModules(ResourceProcessor.groovy:809)
    at org.grails.plugin.resource.ResourceProcessor.this$2$loadModules(ResourceProcessor.groovy)
    at org.grails.plugin.gspresources.GspResourceProcessor.this$2$loadModules(GspResourceProcessor.groovy)
    at org.grails.plugin.resource.ResourceProcessor$this$2$loadModules.callCurrent(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:46)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
    at org.grails.plugin.resource.ResourceProcessor.reloadModules(ResourceProcessor.groovy:1040)
    at org.grails.plugin.gspresources.GspResourceProcessor.reloadModules(GspResourceProcessor.groovy)
    at org.grails.plugin.resource.ResourceProcessor$reloadModules.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
    at ResourcesGrailsPlugin$_closure4_closure22.doCall(ResourcesGrailsPlugin.groovy:222)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.springsource.loaded.ri.OriginalClassInvoker.invoke(OriginalClassInvoker.java:34)
    at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1260)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:231)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:52)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:46)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
    at ResourcesGrailsPlugin$_closure4_closure22.doCall(ResourcesGrailsPlugin.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.springsource.loaded.ri.OriginalClassInvoker.invoke(OriginalClassInvoker.java:34)
    at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1260)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1071)
    at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:901)
    at groovy.lang.Closure.call(Closure.java:415)
    at ResourcesGrailsPlugin$_closure4_closure22.call(ResourcesGrailsPlugin.groovy)
    at groovy.lang.Closure.call(Closure.java:409)
    at ResourcesGrailsPlugin$_closure4_closure22.call(ResourcesGrailsPlugin.groovy)
    at java_util_concurrent_Callable$call.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
    at ResourcesGrailsPlugin$_triggerReload_closure7.doCall(ResourcesGrailsPlugin.groovy:198)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.springsource.loaded.ri.OriginalClassInvoker.invoke(OriginalClassInvoker.java:34)
    at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1260)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:231)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:52)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:46)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
    at ResourcesGrailsPlugin$_triggerReload_closure7.doCall(ResourcesGrailsPlugin.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.springsource.loaded.ri.OriginalClassInvoker.invoke(OriginalClassInvoker.java:34)
    at com.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1260)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1071)
    at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:901)
    at groovy.lang.Closure.call(Closure.java:415)
    at ResourcesGrailsPlugin$_triggerReload_closure7.call(ResourcesGrailsPlugin.groovy)
    at groovy.lang.Closure.call(Closure.java:409)
    at ResourcesGrailsPlugin$_triggerReload_closure7.call(ResourcesGrailsPlugin.groovy)
    at groovy.lang.Closure.run(Closure.java:493)
    at ResourcesGrailsPlugin$_triggerReload_closure7.run(ResourcesGrailsPlugin.groovy)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:680)

**Comment by mckenfra** [comment]
Thanks for testing and finding this bug. Actually this is a tricky one, unfortunately, as the `gsp-resources` plugin relies on behaviour in the `resources` plugin, as follows:

As a general rule, we want to ensure GSP resources are only rendered when all non-GSP resources are ready - because a GSP file might contain references to non-GSP resources (e.g. via a `<g:include>` tag).

The `gsp-resources` plugin achieves this deferred processing of GSPs by using the `resources` plugin's inbuilt support for "synthetic resources". These are resources derived/generated from other resources, and are processed in a final phase, after non-synthetics. So, whenever the `gsp-resources` plugin detects a GSP-type resource, it replaces it with a "synthetic resource" which will eventually do the rendering at the end.

Trouble is, the `resources` plugin also creates a special "synthetic resource" to do the bundling, which it creates when it processes the first resource in the bundle. In the situation causing this bug, the "bundling synthetic resource" is being processed before the "GSP-rendering synthetic resource". Since the GSP hasn't been rendered yet, it throws a null pointer exception.

We need to force the `resources` plugin to process all "GSP-rendering synthetics" before any "bundling synthetics". But there are no easy hooks into the `resources` plugin's processing logic to achieve this ordering, sadly!

My options at the moment are either to get my plugin to override the key method in the `resources` plugin that handles processing, and add special logic to handle "synthetic resource" ordering; or to get the maintainers of the `resources` plugin to add some code to support this dependency ordering of synthetics in a general-purpose "clean" way. The latter way would be preferable, but would require a `resources` plugin release and would therefore probably take longer...

**Comment by skreiker** [comment]
Thanks for this update. In my specific case I plan to change all my  resource to become .js.gsp resource so this bug will not affect me. This way you can plan to fix it with the method you find is most elegant without any constraint of time.
Thanks --Serge

**Comment by skreiker** [comment]
Hello,
It looks like I won't be able to convert all my files to .js.gsp and will have to mix js and js.gsp in the same bundle can we get your plugin to override the key method in the resources plugin that handles processing, and add special logic to handle "synthetic resource" ordering.
Please let me know.
Thank --Serge

**Comment by mckenfra** [comment]
Hi,

Yup, actually I've just been working on that exact thing - i.e. overriding the key method. It's not as pretty a solution as I would have liked, since it involves a direct copy-and-paste of code from the `resources` plugin itself. However, at least it gives us a working solution for the time being. I will then separately ask the `resources` plugin maintainers to restructure their code to allow this special "synthetic resource" ordering in a more generalised way.

I'll let you know when the new version is uploaded and ready for you to try.

**Comment by skreiker** [comment]
Great, Thanks a lot.
--Serge

**Comment by mckenfra** [comment]
Ok, I've re-published version `0.4.2-SNAPSHOT` with the latest fixes. It should automatically download this when you restart or recompile your app.

Hopefully this latest version has now fixed the issues - let me know if it works better for you!

Cheers,
Francis

**Comment by skreiker** [comment]
I just tested and it is now working great. Thanks a lot for fixing it.
